### ISSUE TITLE
L2HellaCacheBank counts voluntary release beats incorrectly.

### ISSUE THREAD

**Issue by kenmcmil** [ucb-bar/uncore#61]
[dump.txt](https://github.com/ucb-bar/uncore/files/326810/dump.txt)

This vcd shows a case where a voluntary release with data comes in on the same clock cycle as the finish of the corresponding acquire (258ps). A grant is then given at 264ps without waiting for the second beat of the release. It looks like this is because, for some reason, pending_irel_beats is not being set correctly when the release is accepted.

**Comment by zhemao** [comment]
Could you rerun the test with the latest version of uncore. We've done some significant refactoring lately. Judging from the signal names, your version is not up-to-date.

**Comment by kenmcmil** [comment]
[dump2.txt](https://github.com/ucb-bar/uncore/files/330896/dump2.txt)

Here's a vcd that shows a similar case on the latest uncore (commit 34f5fad). At 100ps, there is a release ack Grant before the second beat of the release arrives.

**Comment by zhemao** [comment]
Okay, so the issue here is that the client is sending two releases with data for the same block, which shouldn't be possible. At 78 ps and 84 ps, client 0 sends a voluntary release with data to the acquire tracker. But then the one you are seeing at 100ps is an involuntary release, again with data. This should not be possible. If the L1 gets a probe for data it has just voluntarily released, it's release type should not be one that has data, since it has already dropped the cache line.

**Comment by kenmcmil** [comment]
I think the client is correct. At 64ps, the client does a second acquire on the line (the second one is the shared one, but that is legal, since a channel is allowed to re-order the acquires). Then it gets probed. The rules say it has to release, even with a pending acquire, which it does at 78ps. Then the L2 responds to the acquire with a grant at 94ps. The second grant is exclusive, so the client can dirty the line. The client then does a *voluntary* release of this grant with data at 98ps. In other words, the two releases are for two different grants, both exclusive.

**Comment by zhemao** [comment]
But the two acquires are from two different clients, though. As I see it, the order of transactions is as follows.

1. Client 0 acquires
2. Grant for client 0's acquire
3. Client 1 acquires
4. Probe client 0
5. Client 0 voluntary release (w/ data)
6. Grant to client 0's release
7. Client 0 mandatory release (w/ data)

Client 0 should send the release, but the release shouldn't have any data, since it had just voluntarily released it.

**Comment by kenmcmil** [comment]
There are several acquires, but the two relevant ones are at 14ps and 64ps. These are both from client 0 to the same cache block. The two releases are for these acquires.

**Comment by zhemao** [comment]
Oh sorry, you're right, the second acquire to the block is also from client 0. But that second acquire doesn't seem to have been granted yet. In fact, the releases are in response to the probe generated from that second acquire.

But that does raise the question of why we are probing the same client that is making the request. I'll take a closer look at this on Monday.

**Comment by zhemao** [comment]
Okay, on closer inspection, my timeline wasn't really correct. The first release was involuntary, and the second voluntary release was after the cache received the grant for the acquire. So something is strange here.

**Comment by zhemao** [comment]
Okay, I see what's going on here. The sequence of events is as follows.

1. Client 0 sends acquire
2. Cache sends probe to client 0
3. Client 0 sends involuntary release in response to probe
4. Cache sends grant for acquire to client 0
5. Client 0 promptly voluntarily releases the data it just acquired

The issue here is that the cache tracker has sent the grant but hasn't finished the transaction (waiting for data writeback). It actually shouldn't have even accepted the first beat of the voluntary release. Instead, it should have blocked it until it was completed and then let the voluntary release tracker handle it afterwards.

**Comment by zhemao** [comment]
Okay, so one issue is that the voluntary release is coming before the client sends the finish for the grant. That should not be possible. However, it is likely that this issue will still occur even if the release comes after the finish.

Could you update your model to make the release wait on the finish and then run it again? It will probably lead to a similar failure.

**Comment by zhemao** [comment]
I think we've found the cause of the issue and are running tests now. I'll update you when we merge it in.

**Comment by zhemao** [comment]
I've merged a fix into master. Could you pull the latest changes and try again?

**Comment by kenmcmil** [comment]
[dump.txt](https://github.com/ucb-bar/uncore/files/338265/dump.txt)

uncore commit: 99f0c8d

Here's one that may be the same bug. At 30ps, acquire tracker 0 gets the last beat of the voluntary release in the same clock cycle as the finish. It stays in state 0x7, resulting in a deadlock. Keep in mind the releases can be seen before the finish if the finish is delayed in a channel.

**Comment by kenmcmil** [comment]
By the way, most of the error traces now have this form: the final release beat happens in the same clock cycle as the finish.

**Comment by zhemao** [comment]
I don't think it's because of the finish. In this case, the voluntary releases are being sent with the releases in reverse order (beat 1 followed by beat 0). Though the spec doesn't explicitly forbid it, our trackers are assuming that the beats will always come in order. I suspect that's why we're not handling this case properly.

**Comment by zhemao** [comment]
I've talked with Henry about this, and we think we would like to formally disallow starting a multibeat acquire or release on a beat other than 0. The beats must arrive sequentially starting from 0 and continuing to beat N-1.

**Comment by kenmcmil** [comment]
OK, I'll try that and see if it fixes the problem. But a multi-beat grant should still allow arbitrary ordering, right? Or round-robin starting with the critical word?

**Comment by kenmcmil** [comment]
[dump.txt](https://github.com/ucb-bar/uncore/files/344300/dump.txt)

Here's one that shows a finish and voluntary release arriving simultaneously at 30ps. The first beat of the release is word 0, so the beat ordering isn't the problem. Acquire tracker 0 gets stuck in state 7 and never produces a grant.

**Comment by zhemao** [comment]
Multibeat grants will allow starting on any beat, but from there, the beats will need to go in-order.

So, for instance, if the first address beat is 2, the beats will go 2, 3, ... N-1, 0, 1.

**Comment by zhemao** [comment]
It seems that pending_irel_data is not being set to 0 after the second beat as it should be. It doesn't have to do with the concurrent finish request. We've figured out the problem and will soon merge the fix. Once we do, I'll ping you again to rerun the verification. Thanks a lot for helping us track down this bug.

**Comment by zhemao** [comment]
I've merged in all of our changes to master. Could you please run the verification flow again?

**Comment by kenmcmil** [comment]
Looks good. I'm not seeing this error in the traces.
