### ISSUE TITLE
L2HellaCacheBank: cached Acquire and Put interfering 

### ISSUE THREAD

**Issue by kenmcmil** [ucb-bar/uncore#62]
[dump.txt](https://github.com/ucb-bar/uncore/files/338226/dump.txt)

uncore commit: 99f0c8d

In this vcd, there is an Acquire on block 0x400 at 8ps followed by a Put to block 0, word 0 at 10ps. At 24ps the outer Acquire for block 0x400 appears, followed by the outer Acquire for block 0 at 26ps. The outer Grant for block 0 occurs at 28ps, followed by outer Grant for block 0x400 at 36ps. Then inner Grant for 0 at 38ps and inner grant for 0x400 at 44ps.

It appears, however, that the data write to block 0 word 0 is never performed. At 48ps an inner Get on block 0 word 0 occurs. Dirty Release of 0x400 occurs at 54ps, then inner grant for block 0 word 0 at 62ps with incorrect data (not reflecting the prior Put).    

Note, the cache here is 1-way and should be sized here so that 0 and 0x400 collide. So one of these acquires should have caused the other to be evicted.

**Comment by zhemao** [comment]
The blocks actually are being written to two different sets. This is because your CacheIdBits parameter is set to 1, so the index is actually the block address shifted down by 1 and then truncated. I think you want CacheIdBits to be 0, since you only have one bank. In RocketChip, CacheIdBits is set to log2 of the number of banks in the design.

That doesn't explain why one of the writes is getting lost, though, since both addresses are appropriate for this bank.

**Comment by zhemao** [comment]
Also, the reason the put to block 0 looks like it never happens is because the writemask (the upper 32 bits of the union) is set to all 0s. I don't think there's actually any buggy behavior here.
